Initial load for Elastic APM telemetry component.
Avanade/Liquid.Core pull request #31
Opened 2021-12-13 14:05 UTC by marcoshidalgonunes

For reviewers: please confirm the component and its test are according to the Liquid Framework patterns.

2021-12-15 23:40 UTC, lucianareginalino requested changes
The IPipelineBehavior implementation class must be in the project's "implementations" folder. it is not necessary to create a folder named "Mediator" as we are not implementing a component for this purpose.

2021-12-15 23:40 UTC, lucianareginalino commented on src/Liquid.Core.Telemetry.ElasticApm/Extensions/DependencyInjection/IServiceCollectionExtensions.cs
> +        public static IServiceCollection AddElasticApmTelemetry(this IServiceCollection services, IConfiguration configuration)
it is preferable that the injection method names have the prefix "AddLiquid".

2021-12-15 23:40 UTC, lucianareginalino commented on src/Liquid.Core.Telemetry.ElasticApm/MediatR/LiquidPipelineBehavior.cs
> +    public sealed class LiquidPipelineBehavior<TRequest, TResponse> : IPipelineBehavior<TRequest, TResponse>
The name of the class must represent what it is responsible for.
Example: "LiquidElasticApmTelemetryBehavior"

2021-12-16 14:20 UTC, marcoshidalgonunes commented
Requested changes are done. Waiting for confirmation there is all right.

2021-12-16 18:23 UTC, ycamargo commented
We're approving this Pull Request. 
We will create the new pipeline to build, run tests and publish this new component to Nuget. 
We may ask for more changes if the build process shows any problem.

2021-12-16 18:23 UTC, merged